theme: jekyll-theme-midnight

# Welcome to my website!

My name is Landon Knipp, and I am currently a 4th year student at UC Berkeley studying Mechanical Engineering, Aerospace Engineering, and Astrophysics.

